### ISSUE TITLE
Path is hardcord

### ISSUE THREAD

**Issue by whywaita** [unasuke/when-is-the-next-dentoolt#2]
https://github.com/unasuke/when-is-the-next-dentoolt/blob/master/docker-compose.yml#L47

Maybe, Linux?

**Comment by unasuke** [comment]
Path ❓

**Comment by whywaita** [comment]
I don't have `/etc/letsencrypt`...

**Comment by unasuke** [comment]
@whywaita 😊

**Comment by unasuke** [comment]
@whywaita Ok.

I will change it to runnable in local macOS, windows, and non-letsencrypted linux. 😄
